name: 'compressed-size-action'
description: 'Get compressed size differences for every PR'
author: 'Jason Miller'
branding:
  icon: 'archive'
  color: 'purple'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  build-script:
    description: 'The terminal command to build the project'
  benchmark:
    description: 'The command that produces the benchmark output'
  show-total:
    description: 'Show total size and difference.'
    default: 'true'
  collapse-unchanged:
    description: 'Move unchanged files into a separate collapsed table'
    default: 'true'
  omit-unchanged:
    description: 'Exclude unchanged files from the sizes table entirely'
  use-check:
    description: 'Report status as a CI Check instead of using a comment [experimental]'
  minimum-change-threshold:
    description: 'Consider files with changes below this threshold as unchanged. Specified in milliseconds.'
    default: 1
runs:
  using: 'node12'
  main: 'index.js'
